"""build/report.md: what changed against the prototype page and what the merge could not resolve."""
import json
import os
import re
from collections import Counter, defaultdict

from . import config

PROTO_TYPES = {'V': 'vendor', 'R': 'reputation', 'T': 'trainer', 'Q': 'quest', 'D': 'drop'}
LIMIT = 80


def load_prototype(path=config.PROTOTYPE):
    if not os.path.exists(path):
        return None
    with open(path, encoding='utf-8') as f:
        html = f.read()
    i = html.find('const DATA=')
    if i < 0:
        return None
    data, _ = json.JSONDecoder().raw_decode(html, i + len('const DATA='))
    return data


def _types(r):
    t = set()
    for s in r['sources']:
        if s['type'] == 'vendor':
            t.add('reputation' if r['rep'] else 'vendor')
        elif s['type'] in ('object', 'world'):
            t.add('drop')
        else:
            t.add(s['type'])
    return t


def _section(out, title, lines, limit=LIMIT):
    out.append('\n## %s (%d)\n' % (title, len(lines)))
    if not lines:
        out.append('_none_')
        return
    for l in lines[:limit]:
        out.append('- ' + l)
    if len(lines) > limit:
        out.append('- ... %d more' % (len(lines) - limit))


def write(m, path, export_counts):
    proto = load_prototype()
    out = ['# Pipeline report', '',
           'Generated by `pipeline/run.py build`. Server profile: **%s**.' % config.ATLAS_SERVER, '',
           '| Source | Version |', '| --- | --- |']
    for k, v in m.manifest.items():
        if isinstance(v, dict):
            out.append('| %s | %s |' % (k, ' '.join(x for x in (v.get('version'), (v.get('commit') or '')[:10], v.get('date')) if x) or '-'))
    out.append('| extracted | %s |' % m.manifest.get('extracted_at'))
    out.append('\nExported: ' + ', '.join('%d %s' % (n, k) for k, n in export_counts.items()))

    by_key = {}
    for r in m.recipes.values():
        for k in r['legacy_keys']:
            by_key[k] = r
    listed = [r for r in m.recipes.values() if r['listed']]

    out.append('\n## Recipes per profession\n')
    out.append('| Profession | Prototype | Now listed | Added | Dropped | In DB (incl. unlisted) |')
    out.append('| --- | ---: | ---: | ---: | ---: | ---: |')
    added, removed, type_changes, skill_changes = defaultdict(list), defaultdict(list), [], []
    type_counter = Counter()
    for pid in config.PROFESSION_IDS:
        prows = (proto or {}).get('rows', {}).get(pid, [])
        proto_recipes = {}
        for pr in prows:
            r = by_key.get((pid, pr['id']))
            if r is None or not r['listed']:
                why = 'not in the merged data' if r is None else r['unlisted_reason']
                removed[pid].append('%s "%s" (%s)' % (pr['id'], pr['n'], why))
                continue
            proto_recipes[r['id']] = pr
            old_t = {PROTO_TYPES[t] for t in pr['st'].values()}
            new_t = _types(r)
            if old_t != new_t:
                type_changes.append('%s "%s": %s -> %s' % (r['id'], r['name'], '+'.join(sorted(old_t)), '+'.join(sorted(new_t))))
                type_counter['+'.join(sorted(new_t - old_t)) + ' / -' + '-'.join(sorted(old_t - new_t))] += 1
            if pr['s'] != r['skill_req'] and r['skill_req']:
                skill_changes.append('%s "%s": %s -> %s (%s)' % (r['id'], r['name'], pr['s'], r['skill_req'], r['skill_origin']))
        now = [r for r in listed if r['prof'] == pid]
        for r in sorted(now, key=lambda r: (r['skill_req'] or 0, r['name'])):
            if r['id'] not in proto_recipes:
                added[pid].append('%s "%s" skill %s, %s [%s]' % (r['id'], r['name'], r['skill_req'], '+'.join(sorted(_types(r))), ','.join(sorted(r['origins']))))
        total = sum(1 for r in m.recipes.values() if r['prof'] == pid)
        out.append('| %s | %d | %d | %d | %d | %d |' % (pid, len(prows), len(now), len(added[pid]), len(removed[pid]), total))

    for pid in config.PROFESSION_IDS:
        if added[pid]:
            _section(out, 'Added: ' + pid, added[pid], limit=200)
    for pid in config.PROFESSION_IDS:
        if removed[pid]:
            _section(out, 'Dropped: ' + pid, removed[pid], limit=200)
    out.append('\n## Source type changes, summary\n')
    out.append('| Added types / removed types | Recipes |\n| --- | ---: |')
    for k, n in type_counter.most_common():
        out.append('| %s | %d |' % (k, n))
    _section(out, 'Source type changes', type_changes)
    _section(out, 'Skill changes against the prototype', skill_changes)

    for title in sorted(m.notes):
        _section(out, title, sorted(set(m.notes[title])), limit=150)

    gaps = []
    for r in sorted(listed, key=lambda r: r['id']):
        enchant = r['prof'] == 'enchanting' and r['name'].startswith('Enchant ')   # enchants create no item
        miss = [k for k, v in (('skill', r['skill_req']), ('crafted item', r['crafted_item'] or enchant)) if not v]
        if r['crafted_item'] and m.items.get(r['crafted_item'], {}).get('quality') is None:
            miss.append('quality')
        if miss:
            gaps.append('%s %s "%s": no %s' % (r['prof'], r['id'], r['name'], ', '.join(miss)))
    _section(out, 'Listed recipes with missing fields', gaps)
    vendor_ids = {s['npc'] for r in listed for s in r['sources'] if s['type'] in ('vendor', 'trainer') and s.get('npc')}
    nospawn = ['%d "%s"' % (n, m.npcs[n]['name']) for n in sorted(vendor_ids) if n in m.npcs and not m.npcs[n]['spawns']]
    _section(out, 'Vendors / trainers without a location', nospawn)

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out) + '\n')
    return {pid: (len(added[pid]), len(removed[pid])) for pid in config.PROFESSION_IDS}
